import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  attemptedQuestions: {},
  isAttemptedQuestionsLoading: false,
  attemptedQuestionsError: null,
};

const attemptedQuestionSlice = createSlice({
  name: "attemptedQuestion",
  initialState,
  reducers: {
    setAttemptedQuestions: (state, action) => {
      state.attemptedQuestions = action.payload;
    },
    setAttemptedQuestionsLoading: (state, action) => {
      state.isAttemptedQuestionsLoading = action.payload;
    },
    setAttemptedQuestionsError: (state, action) => {
      state.attemptedQuestions = action.payload;
    },
  },
});

// Export actions generated by createSlice
export const {
  setAttemptedQuestions,
  setAttemptedQuestionsLoading,
  setAttemptedQuestionsError,
} = attemptedQuestionSlice.actions;

// Export the reducer to be used in store
export default attemptedQuestionSlice.reducer;
