import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  questions: [],
  isLoading: false,
  error: null,
};

const questionSlice = createSlice({
  name: "question",
  initialState,
  reducers: {
    setQuestions: (state, action) => {
      state.questions = action.payload;
    },
    setQuestionsLoading: (state, action) => {
      state.isLoading = action.payload;
    },
    setQuestionsError: (state, action) => {
      state.error = action.payload;
    },
  },
});

// Export actions generated by createSlice
export const { setQuestions, setQuestionsLoading, setQuestionsError } =
  questionSlice.actions;

// Export the reducer to be used in store
export default questionSlice.reducer;
