import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  questions: {},
  questionAnalysis: {},
  isQuestionsLoading: false,
  questionsError: null,
};

const questionSlice = createSlice({
  name: "question",
  initialState,
  reducers: {
    setQuestions: (state, action) => {
      state.questions = action.payload;
    },
    setQuestionAnalysis: (state, action) => {
      state.questionAnalysis = action.payload;
    },
    setQuestionsLoading: (state, action) => {
      state.isQuestionsLoading = action.payload;
    },
    setQuestionsError: (state, action) => {
      state.questions = action.payload;
    },
  },
});

// Export actions generated by createSlice
export const {
  setQuestions,
  setQuestionsLoading,
  setQuestionsError,
  setQuestionAnalysis,
} = questionSlice.actions;

// Export the reducer to be used in store
export default questionSlice.reducer;
