export const questions = [
  {
    _id: "66d6d2474453061e09e0ec5e",
    questionText:
      "Who among the following rulers of medieval Gujarat surrendered Diu to the Portuguese?",
    questionImage: null,
    questionSource: "UPSC",
    questionOptions: {
      a: "Ahmad Shah",
      b: "Mahmud Begarha",
      c: "Bahadur Shah",
      d: "Muhammad Shah",
    },
    questionCorrectOption: "c",
    questionAnswerExplanation:
      "In 1534, the Bahadur Shah signed the Treaty of Bassein with the Portuguese. By this, he ceded Diu to the Portuguese, as well as other territories of his empire such as Vasai and the islands that today form Mumbai.",
    questionYear: 2023,
    questionAnswerExplanationImage: null,
    questionTopic: "Modern India",
    questionSubtopic: "India in the 18th Century",
  },

  {
    _id: "66d6d2474453061e09e0ec5e",
    questionText:
      "Who among the following rulers of medieval Gujarat surrendered Diu to the Portuguese?",
    questionImage: null,
    questionSource: "UPSC",
    questionOptions: {
      a: "Ahmad Shah",
      b: "Mahmud Begarha",
      c: "Bahadur Shah",
      d: "Muhammad Shah",
    },
    questionCorrectOption: "c",
    questionAnswerExplanation:
      "In 1534, the Bahadur Shah signed the Treaty of Bassein with the Portuguese. By this, he ceded Diu to the Portuguese, as well as other territories of his empire such as Vasai and the islands that today form Mumbai.",
    questionYear: 2023,
    questionAnswerExplanationImage: null,
    questionTopic: "Modern India",
    questionSubtopic: "India in the 18th Century",
    questionDifficultyLevel: null,
    questionCreatedBy: "66d6a754da7c072b65363e8f",
    createdAt: "2024-09-03T09:09:27.455Z",
    updatedAt: "2024-09-03T09:09:27.455Z",
    __v: 0,
  },
  {
    _id: "66d6d3b54453061e09e0ec60",
    questionText:
      "By which one of the following Acts was the Governor General of Bengal designated as the Governor General of India?",
    questionImage: null,
    questionSource: "UPSC",
    questionOptions: {
      a: "The Regulating Act",
      b: "The Pitt's India Act",
      c: "The Charter Act of 1793",
      d: "The Charter Act of 1833",
    },
    questionCorrectOption: "d",
    questionAnswerExplanation:
      "The Government of India Act 1833 or the Charter Act 1833 was an act of the British Parliament, later renamed the St Helena Act 1833. This extended the charter granted to the East India Company for another 20 years. Reorganized the British Indian government. Provision of the Charter Act 1833  Governor-General of Bengal, renamed Governor-General of India. This made Sir William Bentinck the first Governor General of India.  In this way, the administration of the country was unified under one administration.  Governors of Bombay and Madras lose legislative power.  The governor-general had legislative power over all of British India.  The Governor-General of the Council has the power to change, repeal or amend laws affecting all persons and places within the British Indian Territory, whether British, foreigners or Indians. Rice field.  The civil and military affairs of the Company were administered by the Governor-General of the Council.  The Governor’s Council needs him to have 4 members. A fourth member had limited powers.  For the first time, the Government of the Governor-General was called the Government of India and the Council was called the Council of India.",
    questionYear: 2023,
    questionAnswerExplanationImage: null,
    questionTopic: "Modern India",
    questionSubtopic: "India in the 18th Century",
    questionDifficultyLevel: null,
    questionCreatedBy: "66d6a754da7c072b65363e8f",
    createdAt: "2024-09-03T09:15:33.527Z",
    updatedAt: "2024-09-03T09:15:33.527Z",
    __v: 0,
  },
  {
    _id: "66d6d90c4453061e09e0ec64",
    questionText:
      "With reference to Indian History, Alexander Rea, A.H. Longhurst, Robert Sewell, James Burgess and Walter Elliot were associated with",
    questionImage: null,
    questionSource: "UPSC",
    questionOptions: {
      a: "archaeological excavations",
      b: "establishment of English Press in Colonial India",
      c: "establishment of Churches in Princely States",
      d: "construction of railways in Colonial India",
    },
    questionCorrectOption: "a",
    questionAnswerExplanation:
      "1. Alexander Rea: He was an archaeologist who served as the Director-General of Archaeology in British India. Rea conducted excavations and surveys in various regions of India, including ancient sites like Taxila and Amaravati. He made important discoveries and contributions to the understanding of Indian history and art. 2. A.H. Longhurst: A.H. Longhurst was an archaeologist and art historian who specialized in the study of Indian architecture and sculpture. He conducted extensive research and documentation of historical sites and monuments in India. Longhurst authored several books and publications on Indian art and architecture. 3. Robert Sewell: Robert Sewell was a British civil servant and historian. He is known for his work on the history and administration of the Vijayanagara Empire. Sewell’s book, “A Forgotten Empire: Vijayanagar - A Contribution to the History of India,” is considered a seminal work on the subject. 4. James Burgess: James Burgess was a Scottish archaeologist and epigraphist who played a crucial role in the documentation and preservation of Indian archaeological sites. He conducted excavations and surveys across different regions of India and made significant contributions to the understanding of Indian history, architecture, and culture. 5. Walter Elliot: Walter Elliot was a British administrator and politician who also had a keen interest in archaeology. He conducted archaeological excavations in various parts of India, particularly in the region of Tamil Nadu. Elliot’s work contributed to the exploration and preservation of historical sites in South India. These individuals made important contributions to the study of Indian history and archaeology, helping to uncover and document the rich cultural heritage of the country.",
    questionYear: 2023,
    questionAnswerExplanationImage: null,
    questionTopic: "Modern India",
    questionSubtopic: "India in the 18th Century",
    questionDifficultyLevel: null,
    questionCreatedBy: "66d6a754da7c072b65363e8f",
    createdAt: "2024-09-03T09:38:20.532Z",
    updatedAt: "2024-09-03T09:38:20.532Z",
    __v: 0,
  },
  {
    _id: "66d6e47a4453061e09e0ec66",
    questionText:
      "With reference to Indian history, consider the following statements:  1. The Dutch established their factories/ warehouses on the east coast on lands granted to them by the Gajapati rulers. 2. Alfonso de Albuquerque captured Goa from the Bijapur Sultanate. 3. The English East India Company established a factory at Madras on a plot of land leased from a representative of the Vijayanagara empire. Which of the statements given above are correct?",
    questionImage: null,
    questionSource: "UPSC",
    questionOptions: {
      a: "1 and 2 only",
      b: "2 and 3 only",
      c: "1 and 3 only",
      d: "1, 2 and 3",
    },
    questionCorrectOption: "b",
    questionAnswerExplanation:
      "Statement 1 is incorrect: The first factory established by Dutch was in Masulipatnam in 1605, whereas Gajapati’s rule lasted till the middle of the 16th century. Statement 2 is correct: Albuquerque acquired Goa from the Sultan of Bijapur in 1510. Statement 3 is correct. The rulers of Vijayanagara appointed chieftains called Nayaks to rule independently in their areas. Darmala Venkatadri Nayaka was in charge of what is Chennai today. He gave land to the British on which they established settlements of British factory workers and merchants.",
    questionYear: 2022,
    questionAnswerExplanationImage: null,
    questionTopic: "Modern India",
    questionSubtopic: "India in the 18th Century",
    questionDifficultyLevel: null,
    questionCreatedBy: "66d6a754da7c072b65363e8f",
    createdAt: "2024-09-03T10:27:06.995Z",
    updatedAt: "2024-09-03T10:27:06.995Z",
    __v: 0,
  },
  {
    _id: "66d6e4e74453061e09e0ec68",
    questionText:
      "In the first quarter of the seventeenth century, in which of the following was/ were the factory/factories of the English East India Company located?  1. Broach 2. Chicacole 3. Trichinopoly Select the correct answer using the code given below:",
    questionImage: null,
    questionSource: "UPSC",
    questionOptions: {
      a: "1 only",
      b: "1 and 2",
      c: "3 only",
      d: "2 and 3",
    },
    questionCorrectOption: "a",
    questionAnswerExplanation:
      "Option (a) is correct: The English East India Company had very humble beginnings in India. Captain Hawkins arrived in the court of Jahangir in April 1609. But the mission to establish a factory at Surat did not succeed due to opposition from the Portuguese, and Hawkins left Agra in November 1611. By 1623 it had established factories (trading posts) at Surat, Broach, Ahmedabad, Agra, and Masulipatam. From the very beginning, it tried to combine trade and diplomacy with war and control of the territory where its factories were situated. The factories of the British East India Company were not located in Chicacole and Trichinopoly in the first quarter of the 17th century.",
    questionYear: 2021,
    questionAnswerExplanationImage: null,
    questionTopic: "Modern India",
    questionSubtopic: "India in the 18th Century",
    questionDifficultyLevel: null,
    questionCreatedBy: "66d6a754da7c072b65363e8f",
    createdAt: "2024-09-03T10:28:55.937Z",
    updatedAt: "2024-09-03T10:28:55.937Z",
    __v: 0,
  },
  {
    _id: "66d6e5634453061e09e0ec6a",
    questionText:
      "Which of the following statements correctly explains the impact of the Industrial Revolution on India during the first half of the nineteenth century?",
    questionImage: null,
    questionSource: "UPSC",
    questionOptions: {
      a: "Indian handicrafts were ruined.",
      b: "Machines were introduced in the Indian textile industry in large numbers.",
      c: "Railway lines were laid in many parts of the country.",
      d: "Heavy duties were imposed on the imports of British manufactures.",
    },
    questionCorrectOption: "a",
    questionAnswerExplanation:
      "India was a major exporter for textiles in the early 18th century, but by the middle of the 19th century it had lost all of its export market and much of its domestic market. At the beginning of the Industrial Revolution, cotton industries were developed in England which made industrial groups worry about imports from other countries. The government was pressured to impose import duties on cotton textiles so that Manchester goods could sell in Britain without facing any competition from outside. Option (a) is correct: At the same time, the East India Company was also persuaded by industrialists to sell British manufactures in Indian markets as well. Exports of British cotton goods increased dramatically in the early nineteenth century and the export market of the cotton weavers collapsed. Produced by machines at lower costs, the imported cotton goods were so cheap that weavers could not easily compete with them. By the 1850s, reports from most weaving regions of India narrated stories of decline and desolation. Thus, Indian handicrafts were ruined as one of the impacts of the Industrial Revolution.  Elimination Technique: Due to the industrial Revolution Indian handicrafts were ruined and not the other way around. Machines were introduced in the later time. Railway line was for the support of industrialisation in Britain.",
    questionYear: 2020,
    questionAnswerExplanationImage: null,
    questionTopic: "Modern India",
    questionSubtopic: "India in the 18th Century",
    questionDifficultyLevel: null,
    questionCreatedBy: "66d6a754da7c072b65363e8f",
    createdAt: "2024-09-03T10:30:59.474Z",
    updatedAt: "2024-09-03T10:30:59.474Z",
    __v: 0,
  },
];
